### ISSUE TITLE
Another program has the same name

### ISSUE THREAD

**Issue by mgiugliano** [dmulholland/mp3cat#13]
It might be worth specifying that this is a distinct project from https://tomclegg.ca/mp3cat

**Comment by niXta1** [comment]
https://github.com/tomclegg/mp3cat

**Comment by niXta1** [comment]
Known issue https://github.com/dmulholland/mp3cat/issues/11, @mgiugliano can you close this?

**Comment by mgiugliano** [comment]
I could not find where you mentioned (in the ReadMe.md or in the project web page, help, etc.) that a distinct project exists with the same name - this project is at https://github.com/tomclegg/mp3cat

**Comment by dmulholl** [comment]
These kind of name clashes actually happen all the time - here's another one:

https://mp3-cat.en.softonic.com

People have been releasing software for over 50 years now so it's bound to happen occasionally and it's only going to get worse over time as the namespace gets more and more crowded. I don't think it's really a problem worth worrying about though for two obscure programs to share the same name. Now if I decided to release an application called `photoshop` or `gmail`, that would be different :)

On the other hand, I am definitely considering renaming the utility to `mp3meld` as my original intention to create a pipeline utility similar in operation to `cat` turned out to be impossible to implement for variable bit-rate MP3 files, so the current name is a little misleading.

**Comment by mgiugliano** [comment]
I understand perfectly. I had politely proposed to mention the existence of another project by the same name, in the same spirit wikipedia disambiguates entries upfront. Feel free - as you should have had - to ignore my comment entirely.
